export const customerData = [
  {
    name: "Stalked Wild Petunia",
    email: "msidworth0@yale.edu",
    phone: "205-683-7064",
    delivery: "5 Farwell Road",
    orders_completed: 95,
  },
  {
    name: "Orthotrichum Moss",
    email: "adare1@harvard.edu",
    phone: "444-581-4465",
    delivery: "72782 Sutherland Court",
    orders_completed: 92,
  },
  {
    name: "Letrouitia Lichen",
    email: "cwilliams2@sphinn.com",
    phone: "211-532-4352",
    delivery: "0 Logan Trail",
    orders_completed: 64,
  },
  {
    name: "Terra Alta Blackberry",
    email: "hwinsbury3@wordpress.org",
    phone: "230-774-8625",
    delivery: "521 Moland Park",
    orders_completed: 100,
  },
  {
    name: "Dissotis",
    email: "qdolan4@weather.com",
    phone: "694-877-5505",
    delivery: "509 Lakewood Plaza",
    orders_completed: 63,
  },
  {
    name: "Western Moss Heather",
    email: "fsomerville5@cnet.com",
    phone: "205-682-6566",
    delivery: "312 Kennedy Street",
    orders_completed: 77,
  },
  {
    name: "Sabaigrass",
    email: "gpaulmann6@sphinn.com",
    phone: "495-758-6419",
    delivery: "99 Sage Center",
    orders_completed: 97,
  },
  {
    name: "Burro Blanco",
    email: "mocrowley7@theguardian.com",
    phone: "139-970-9096",
    delivery: "6 Westport Circle",
    orders_completed: 37,
  },
  {
    name: "Geno Geno",
    email: "cbascombe8@narod.ru",
    phone: "996-512-8700",
    delivery: "6 Judy Avenue",
    orders_completed: 99,
  },
  {
    name: "California Indigobush",
    email: "vrohloff9@pagesperso-orange.fr",
    phone: "517-370-6890",
    delivery: "4986 Donald Street",
    orders_completed: 85,
  },
  {
    name: "Volantines Preciosos",
    email: "msearla@reference.com",
    phone: "258-450-9780",
    delivery: "9 Mitchell Center",
    orders_completed: 96,
  },
  {
    name: "Pogonatum Moss",
    email: "gedgeworthb@fc2.com",
    phone: "210-400-2374",
    delivery: "5542 Dapin Plaza",
    orders_completed: 43,
  },
  {
    name: "Trichosanthes",
    email: "lmacrinnc@networksolutions.com",
    phone: "832-573-2641",
    delivery: "9010 Hovde Avenue",
    orders_completed: 44,
  },
  {
    name: "Gray Cryptantha",
    email: "vbrotherheedd@pbs.org",
    phone: "282-697-4186",
    delivery: "84 Dahle Center",
    orders_completed: 42,
  },
  {
    name: "Clubhair Mariposa Lily",
    email: "cdowse@illinois.edu",
    phone: "471-371-8868",
    delivery: "9203 Menomonie Pass",
    orders_completed: 10,
  },
];
export const customerHeader = [
  "Name",
  "Email",
  "Phone",
  "Delivery address",
  "Orders Completed",
];

export const headers = [
  "Name",
  "Email",
  "Phone",
  "Location",
  "No of Riders",
  "No of Deliveries",
  "Status",
];
const overviewHeaders = [
  "Date",
  "Order ID",
  "Rider ID",
  "Pickup time",
  "Delivery time",
  "Distance (KM)",
  "Status",
];
export const vendorHeader = [
  "Name",
  "Email",
  "Phone",
  "Location",
  "Orders Complete",
  "Available",
];
export const orderHeader = [
  "Date",
  "Order ID",
  "Rider ID",
  "Pick up time",
  "Delivery time",
  "Distance (KM)",
  "Status",
  "Actions",
];
export const paymentHeader = [
  "Vendor Name",
  "Vendor ID",
  "Amount(N)",
  "Date",
  "Time",
  "Status",
];
